[package]
name = "starknetid_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starknet = { git = "https://github.com/Th0rgal/starknet-rs.git", branch = "feat/starknet-id" }
axum = "0.6.18"
futures = "0.3.28"
mongodb = "2.5.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
toml = "0.7.4"
tower-http = { version = "0.4.0", features = ["cors"] }
chrono = "0.4.24"
reqwest = "0.11.20"
ark-ff = "0.4.2"
hex = "0.4.3"
