[server]
port = 8080

[databases]
[databases.starknetid]
name = "starknetid"
connection_string = "xxxxxx"
[databases.sales]
name = "sales"
connection_string = "xxxxxx"

[contracts]
starknetid = "0xXXXXXXXXXXXX"
naming = "0xXXXXXXXXXXXX"
verifier = "0xXXXXXXXXXXXX"
old_verifier = "0xXXXXXXXXXXXX"
pop_verifier = "0xXXXXXXXXXXXX"
pp_verifier = "0xXXXXXXXXXXXX"

[starkscan]
api_url = "https://api-testnet.starkscan.co/api/v0/"
api_key = "xxxxxx"

[custom_resolvers]
"0xXXXXXXXXXXXX" = ["domain.stark"]
