[server]
port = 8080

[database]
name = "starknetid"
connection_string = "xxxxxx"

[contracts]
starknetid = "0xXXXXXXXXXXXX"
naming = "0xXXXXXXXXXXXX"
verifier = "0xXXXXXXXXXXXX"
old_verifier = "0xXXXXXXXXXXXX"
pop_verifier = "0xXXXXXXXXXXXX"
